import "./globals.css";
import ThemeProviders from "@/providers/ThemeProviders";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import {Toaster} from "react-hot-toast";
import {AuthProvider} from "@/context/AuthProvider";
import ReduxProvider from "@/providers/ReduxProvider";

export const metadata = {
    title: "Sadhona",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="dark:bg-primary bg-secondaryBg text-normal">
                <ReduxProvider>
                    <AuthProvider>
                        <ThemeProviders>
                            <Toaster position="bottom-right" />
                            <Header />
                            {children}
                            <Footer />
                        </ThemeProviders>
                    </AuthProvider>
                </ReduxProvider>
            </body>
        </html>
    );
}
